server:
  port: 8080  # Explicitly set if not already

gateway:
  routes:
    user-service-url: ${USER_SERVICE_URL:http://localhost:8081}
    catalog-service-url: ${CATALOG_SERVICE_URL:http://localhost:8082}
