server:
  port: ${SERVER_PORT:8080}

spring:
  data:
    redis:

      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}   # <--- ADD THIS LINE
      database: 0              # optional, default 0
      timeout: 5s          # optional
      lettuce: # if using Lettuce (default)
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          read-timeout: 5s
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: ${MASTER_DB_URL:jdbc:mysql://10.196.2.223:3306/master_tenant_db?useSSL=false&serverTimezone=UTC}
      username:  ${MASTER_DB_USERNAME:root}
      password:  ${MASTER_DB_PASSWORD:root}
      maximumPoolSize: 10
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
saas:
  common:
    jwt:
      enabled: ${JWT_ENABLED:false}
      secret: ${JWT_SECRET:default_Secret}
      access-token-expiration-ms: 3600000    # 1 hour
      refresh-token-expiration-ms: 604800000 # 1 week
    redis:
      enabled: true
    kafka:
      enabled: ${KAFKA_ENABLED:false}
      bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
      group: user-microservice-group
    mqtt:
      enabled: ${MQTT_ENABLED:false}
      broker: ${MQTT_BROKER:tcp://localhost:8083}
      username: ${MQTT_USERNAME:username}    # 1 hour
      password: ${MQTT_PASSWORD:default_password}
      clientId: ${MQTT_GROUP:user}

logging:
  level:
    com.saas.platform: ${LOG_LEVEL:DEBUG}
