name: Build & Release Docker

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Service name to build (folder name)'
        required: true
        default: 'user-service'
      tag:
        description: 'Optional tag for Docker image'
        required: true
        default: '1.0.0'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      GITHUB_USERNAME: ${{ secrets.USERNAME }}
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/wrapper/dists
            ~/.gradle/caches
          key: gradle-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-
      

      - name: Build JAR with Gradle
        working-directory: ${{ github.event.inputs.service }}
        run: |
          chmod +x ./gradlew
          ./gradlew clean bootJar --no-daemon \
          -Pgpr.user=${{ secrets.USERNAME }} \
          -Pgpr.token=${{ secrets.TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        working-directory: ${{ github.event.inputs.service }}
        run: |
          TAG=${{ github.event.inputs.tag }}
          if [ -z "$TAG" ]; then
            TAG="latest"
          fi
          # Build multi-arch image
          docker buildx build \
            --platform linux/arm64 \
            -t ${{ secrets.DOCKER_USERNAME }}/${{ github.event.inputs.service }}:$TAG \
            -t ${{ secrets.DOCKER_USERNAME }}/${{ github.event.inputs.service }}:latest \
            --push .
